# Generated by Django 4.2.8 on 2023-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('ingredient1', models.CharField(max_length=50, unique=True)),
                ('ingredient2', models.CharField(max_length=50, unique=True)),
                ('ingredient3', models.CharField(max_length=50, unique=True)),
                ('ingredient4', models.CharField(max_length=50, unique=True)),
                ('ingredient5', models.CharField(max_length=50, unique=True)),
                ('amount1', models.IntegerField()),
                ('amount2', models.IntegerField()),
                ('amount3', models.IntegerField()),
                ('amount4', models.IntegerField()),
                ('amount5', models.IntegerField()),
            ],
        ),
    ]
