# Generated by Django 4.2.8 on 2023-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemStatus', models.CharField(choices=[('STOPPED', 'STOPPED'), ('RUNNING', 'RUNNING')], default='STOPPED', max_length=50)),
            ],
        ),
    ]
