# Generated by Django 4.2.8 on 2023-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='amount1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amount2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amount3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amount4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amount5',
            field=models.FloatField(),
        ),
    ]
