# Generated by Django 4.2.8 on 2023-12-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_flavor_amount1_alter_flavor_amount2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=20)),
                ('baudrate', models.IntegerField()),
                ('timeout', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='id',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
