# Generated by Django 4.2.8 on 2023-12-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_devicesettings_remove_flavor_id_alter_flavor_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesettings',
            options={'verbose_name': 'Device Settings'},
        ),
    ]
