# Generated by Django 4.2.8 on 2023-12-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_actuator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='ingredient5',
        ),
    ]
